#pragma once
#include "stdafx.h"
#include "util.h"
#include "ubigint.h"
#include <assert.h>

//forward decls
int problem1();
int problem2();
int problem3();
int problem4();
int problem5();
int problem6();
int problem7(int numPrime);
uint64_t problem8();
int problem9();
uint64_t problem10();
int problem11();
int problem12();
ubigint problem13();
int problem14();
uint64_t problem15();
int problem16();
int problem17();
int problem18();
int problem19();
int problem20();
int problem21();
int problem22();